name: on-tags-ignore

on:
  push:
    branches:
      - main

    tags-ignore:
      - "v**"

  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo run
